<?php

namespace apptest;
/**
 * AdminModule, модуль для обработки страниц admin
 */
class AdminModule extends AHandle
{
    public function handle(string $request): ?string
    {
        if ($request == 'isAdmin')
        {
            echo $this->execute();
        }
        return parent::handle($request); // TODO: Change the autogenerated stub
    }

    public function execute()
    {
        return 'AdminModule execute';
    }
}