<?php

namespace apptest;
/**
 * RestModule, модуль для обработки страниц rest api
 */
class RestModule extends AHandle
{
    public function handle(string $request): ?string
    {
        if ($request == 'isRest')
        {
            echo $this->execute();
        }
        return parent::handle($request); // TODO: Change the autogenerated stub
    }

    public function execute()
    {
        return 'RestModule execute';
    }
}